// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ChappieUI_Launcher

#include "ui.h"

///////////////////// VARIABLES ////////////////////
void StateBarDropDown_Animation(lv_obj_t * TargetObject, int delay);
void StateBarPullUp_Animation(lv_obj_t * TargetObject, int delay);


void ui_Myapp1_Screeen_init(void);
lv_obj_t * ui_Myapp1;
lv_obj_t * ui_testapp;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_saying;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void myapp_ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Myapp1_Screeen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Myapp1);
}
