// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// SCREEN: ui_setting
void ui_setting_screen_init(void);
void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Setting;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_time1;
// SCREEN: ui_setting2
void ui_setting2_screen_init(void);
void ui_event_setting2(lv_event_t * e);
extern lv_obj_t * ui_setting2;
extern lv_obj_t * ui_Setting4;
void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_saying1;
extern lv_obj_t * ui_time5;
// SCREEN: ui_setting3
void ui_setting3_screen_init(void);
void ui_event_setting3(lv_event_t * e);
extern lv_obj_t * ui_setting3;
extern lv_obj_t * ui_Setting5;
void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_time6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_568895744);    // assets/碳.png
LV_IMG_DECLARE(ui_img_1107777675);    // assets/善.png
LV_IMG_DECLARE(ui_img_708483677);    // assets/猪.png

LV_FONT_DECLARE(ui_font_MontserratBold48);


void mysetting_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
