// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_setting3_screen_init(void)
{
    ui_setting3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setting3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting5 = lv_obj_create(ui_setting3);
    lv_obj_set_width(ui_Setting5, 280);
    lv_obj_set_height(ui_Setting5, 240);
    lv_obj_set_align(ui_Setting5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting5, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_Setting5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Setting5, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Setting5, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_Setting5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting5, lv_color_hex(0xACD6EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Setting5);
    lv_img_set_src(ui_Image6, &ui_img_708483677);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 280
    lv_obj_set_x(ui_Image6, 35);
    lv_obj_set_y(ui_Image6, 18);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 100);

    ui_time6 = lv_label_create(ui_Setting5);
    lv_obj_set_width(ui_time6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time6, -99);
    lv_obj_set_y(ui_time6, -50);
    lv_obj_set_align(ui_time6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time6, "15\n05");
    lv_obj_set_style_text_align(ui_time6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time6, &ui_font_MontserratBold48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setting3, ui_event_setting3, LV_EVENT_ALL, NULL);

}
