// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_setting2_screen_init(void)
{
    ui_setting2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setting2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting4 = lv_obj_create(ui_setting2);
    lv_obj_set_width(ui_Setting4, 280);
    lv_obj_set_height(ui_Setting4, 240);
    lv_obj_set_align(ui_Setting4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Setting4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Setting4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Setting4, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_Setting4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting4, lv_color_hex(0xF6D239), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Setting4);
    lv_img_set_src(ui_Image5, &ui_img_1107777675);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 280
    lv_obj_set_x(ui_Image5, 30);
    lv_obj_set_y(ui_Image5, 0);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 120);

    ui_saying1 = lv_label_create(ui_Setting4);
    lv_obj_set_width(ui_saying1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saying1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_saying1, -95);
    lv_obj_set_y(ui_saying1, -98);
    lv_obj_set_align(ui_saying1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saying1, "Hello !!!");
    lv_obj_set_style_text_color(ui_saying1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_saying1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_saying1, &ui_font_MontserratBold48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time5 = lv_label_create(ui_Setting4);
    lv_obj_set_width(ui_time5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time5, -105);
    lv_obj_set_y(ui_time5, 53);
    lv_obj_set_align(ui_time5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time5, "15\n05");
    lv_obj_set_style_text_color(ui_time5, lv_color_hex(0x451B71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time5, &ui_font_MontserratBold48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image5, ui_event_Image5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setting2, ui_event_setting2, LV_EVENT_ALL, NULL);

}
