// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ChappieUI_Launcher

#include "../ui.h"

void ui_Myapp1_Screeen_init(void)
{
    
    ui_Myapp1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Myapp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_testapp = lv_obj_create(ui_Myapp1);
    lv_obj_set_width(ui_testapp, 280);
    lv_obj_set_height(ui_testapp, 240);
    lv_obj_set_align(ui_testapp, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_testapp, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_testapp, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_testapp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_testapp, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_testapp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_testapp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_testapp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_testapp);
    lv_img_set_src(ui_Image1, &ui_img_1385334836);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 207
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 230
    lv_obj_set_x(ui_Image1, -3);
    lv_obj_set_y(ui_Image1, 12);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 350);

    ui_Switch1 = lv_switch_create(ui_testapp);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 98);
    lv_obj_set_y(ui_Switch1, -94);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Switch1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_saying = lv_label_create(ui_testapp);
    lv_obj_set_width(ui_saying, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saying, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_saying, -89);
    lv_obj_set_y(ui_saying, -99);
    lv_obj_set_align(ui_saying, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saying, "Good job!");
    lv_obj_set_style_text_font(ui_saying, &ui_font_FontUbuntuBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

}
