// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ChappieUI_Launcher

#include "../ui.h"

void ui_ScreenLauncher_screen_init(void)
{
    ui_ScreenLauncher = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLauncher, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelDesktop = lv_obj_create(ui_ScreenLauncher);
    lv_obj_set_width(ui_PanelDesktop, 280);
    lv_obj_set_height(ui_PanelDesktop, 240);
    lv_obj_set_align(ui_PanelDesktop, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_PanelDesktop, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_PanelDesktop, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_PanelDesktop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDesktop, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDesktop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDesktop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDesktop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelControlPad = lv_obj_create(ui_PanelDesktop);
    lv_obj_set_width(ui_PanelControlPad, 280);
    lv_obj_set_height(ui_PanelControlPad, 240);
    lv_obj_set_align(ui_PanelControlPad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelControlPad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_PanelControlPad, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_PanelControlPad, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_PanelControlPad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelControlPad, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelControlPad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelControlPad, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelControlPad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBrightness = lv_slider_create(ui_PanelControlPad);
    lv_slider_set_range(ui_ArcBrightness, 20, 255);
    lv_slider_set_value(ui_ArcBrightness, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ArcBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ArcBrightness, 20,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_ArcBrightness, 150);
    lv_obj_set_height(ui_ArcBrightness, 11);
    lv_obj_set_x(ui_ArcBrightness, 1);
    lv_obj_set_y(ui_ArcBrightness, 32);
    lv_obj_set_align(ui_ArcBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBrightness, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags


    ui_BrightnessValue = lv_label_create(ui_PanelControlPad);
    lv_obj_set_width(ui_BrightnessValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessValue, 100);
    lv_obj_set_y(ui_BrightnessValue, 34);
    lv_obj_set_align(ui_BrightnessValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessValue, "100");
    lv_obj_set_style_text_color(ui_BrightnessValue, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrightnessValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAutoScreenOff = lv_btn_create(ui_PanelControlPad);
    lv_obj_set_width(ui_ButtonAutoScreenOff, 155);
    lv_obj_set_height(ui_ButtonAutoScreenOff, 38);
    lv_obj_set_x(ui_ButtonAutoScreenOff, -5);
    lv_obj_set_y(ui_ButtonAutoScreenOff, 81);
    lv_obj_set_align(ui_ButtonAutoScreenOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAutoScreenOff, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAutoScreenOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonAutoScreenOff, 19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonAutoScreenOff, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAutoScreenOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonAutoScreenOff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonAutoScreenOff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonAutoScreenOff, lv_color_hex(0x7FD19A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonAutoScreenOff, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelBtnAutoScreenOff = lv_label_create(ui_ButtonAutoScreenOff);
    lv_obj_set_width(ui_LabelBtnAutoScreenOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnAutoScreenOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnAutoScreenOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnAutoScreenOff, "AutoScreenOff");
    lv_obj_set_style_text_color(ui_LabelBtnAutoScreenOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnAutoScreenOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelBtnAutoScreenOff, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelBtnAutoScreenOff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnAutoScreenOff, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonInfos = lv_btn_create(ui_PanelControlPad);
    lv_obj_set_width(ui_ButtonInfos, 60);
    lv_obj_set_height(ui_ButtonInfos, 60);
    lv_obj_set_x(ui_ButtonInfos, -90);
    lv_obj_set_y(ui_ButtonInfos, -53);
    lv_obj_set_align(ui_ButtonInfos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonInfos, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonInfos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonInfos, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfos, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonInfos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonInfos, &ui_img_img_infos_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonInfos, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonInfos, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonInfos, lv_color_hex(0x7FD19A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonInfos, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ButtonWifi = lv_btn_create(ui_PanelControlPad);
    lv_obj_set_width(ui_ButtonWifi, 60);
    lv_obj_set_height(ui_ButtonWifi, 60);
    lv_obj_set_x(ui_ButtonWifi, 0);
    lv_obj_set_y(ui_ButtonWifi, -53);
    lv_obj_set_align(ui_ButtonWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonWifi, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonWifi, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonWifi, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonWifi, &ui_img_img_wifi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonWifi, lv_color_hex(0x7FD19A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonWifi, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ButtonBle = lv_btn_create(ui_PanelControlPad);
    lv_obj_set_width(ui_ButtonBle, 60);
    lv_obj_set_height(ui_ButtonBle, 60);
    lv_obj_set_x(ui_ButtonBle, 90);
    lv_obj_set_y(ui_ButtonBle, -53);
    lv_obj_set_align(ui_ButtonBle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBle, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonBle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonBle, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonBle, lv_color_hex(0xA6B4CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonBle, &ui_img_img_ble_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonBle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonBle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonBle, lv_color_hex(0x7FD19A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonBle, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelHome = lv_obj_create(ui_PanelDesktop);
    lv_obj_set_width(ui_PanelHome, 280);
    lv_obj_set_height(ui_PanelHome, 240);
    lv_obj_set_x(ui_PanelHome, 280);
    lv_obj_set_y(ui_PanelHome, 0);
    lv_obj_set_align(ui_PanelHome, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_PanelHome, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_PanelHome, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_PanelHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHome, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHomeTime = lv_label_create(ui_PanelHome);
    lv_obj_set_width(ui_LabelHomeTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHomeTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHomeTime, 1);
    lv_obj_set_y(ui_LabelHomeTime, -38);
    lv_obj_set_align(ui_LabelHomeTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHomeTime, "18:01");
    lv_obj_set_style_text_color(ui_LabelHomeTime, lv_color_hex(0xFFCC4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHomeTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHomeTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHomeTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHomeTime, &ui_font_FontUbuntuBold96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHomeDate = lv_label_create(ui_PanelHome);
    lv_obj_set_width(ui_LabelHomeDate, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_LabelHomeDate, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_LabelHomeDate, 57);
    lv_obj_set_y(ui_LabelHomeDate, 85);
    lv_obj_set_align(ui_LabelHomeDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHomeDate, "Sat, Mar 18");
    lv_obj_set_style_text_color(ui_LabelHomeDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHomeDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHomeDate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHomeDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHomeDate, &ui_font_FontUbuntuBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgStateBar = lv_img_create(ui_ScreenLauncher);
    lv_img_set_src(ui_ImgStateBar, &ui_img_img_statebar_png);
    lv_obj_set_width(ui_ImgStateBar, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_ImgStateBar, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_ImgStateBar, 0);
    lv_obj_set_y(ui_ImgStateBar, -135);
    lv_obj_set_align(ui_ImgStateBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgStateBar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgStateBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgStateBar, 255);

    ui_LabelStateBarTime = lv_label_create(ui_ImgStateBar);
    lv_obj_set_width(ui_LabelStateBarTime, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_LabelStateBarTime, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_LabelStateBarTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStateBarTime, "21:15");
    lv_obj_set_style_text_color(ui_LabelStateBarTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStateBarTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelStateBarTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelStateBarTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStateBarTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStateBarTime, &ui_font_FontUbuntuBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBattery = lv_img_create(ui_ImgStateBar);
    lv_img_set_src(ui_ImgBattery, &ui_img_img_battery_png);
    lv_obj_set_width(ui_ImgBattery, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImgBattery, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_ImgBattery, 100);
    lv_obj_set_y(ui_ImgBattery, -1);
    lv_obj_set_align(ui_ImgBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryBar = lv_bar_create(ui_ImgBattery);
    lv_bar_set_value(ui_BatteryBar, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar, 17);
    lv_obj_set_height(ui_BatteryBar, 9);
    lv_obj_set_x(ui_BatteryBar, -2);
    lv_obj_set_y(ui_BatteryBar, 0);
    lv_obj_set_align(ui_BatteryBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0x4D5B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ArcBrightness, ui_event_ArcBrightness, LV_EVENT_ALL, NULL);

}
